
                <div class="col-md-4">
                    <div class="stat">
                        <div class="count-container clearfix">
                            <div class="float-left"><i class="la la-institution"></i></div>
                            <div class="float-right">
                                <div class="count" style="color: #FA5799;"><?php echo model('manager::manager')->countLabels()?></div>
                            </div>
                        </div>
                        <div class="stat-title"><?php _l('manager::record_labels')?></div>
                    </div>
                </div>
