
                <div class="col-md-4">
                    <div class="stat">
                        <div class="count-container clearfix">
                            <div class="float-left"><i class="la la-institution"></i></div>
                            <div class="float-right">
                                <div class="count" style="color: #FA5799;">
                                    <?php echo model('manager::manager')->countLabels()?>
                                </div>
                            </div>
                        </div>
                        <div class="stat-title"><?php _l('manager::record_labels')?></div>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="stat">
                        <div class="count-container clearfix">
                            <div class="float-left"><i class="la la-download"></i></div>
                            <div class="float-right">
                                <div class="count" style="color: #2196F3;">
                                    <?php if (config('anonymous_downloads') && config('sum_anonymous_downloads')): ?>
                                        <?php echo model('manager::manager')->countAllDownloads() + model('manager::manager')->countAllAnonymousDownloads()?>   
                                    <?php else:?>   
                                        <?php echo model('manager::manager')->countAllDownloads()?>                         
                                    <?php endif;?>                           
                                </div>
                            </div>
                        </div>
                        <div class="stat-title"><?php _l('downloads')?></div>
                    </div>
                </div>

                <?php if (config('anonymous_downloads') && !config('sum_anonymous_downloads')): ?>
                <div class="col-md-4">
                    <div class="stat">
                        <div class="count-container clearfix">
                            <div class="float-left"><i class="fa fa-cloud-download"></i></div>
                            <div class="float-right">
                                <div class="count" style="color: #FF5722;">
                                    <?php echo model('manager::manager')->countAllAnonymousDownloads()?>
                                </div>
                            </div>
                        </div>
                        <div class="stat-title"><?php _l('manager::anonymous')?> <?php _l('downloads')?></div>
                    </div>
                </div>
                <?php endif;?> 
