<hr/>

<h6><?php _l('labeler::label_management')?></h6>
<hr/>
<div class="form-group row">
    <label for="staticEmail" class="col-sm-3 col-form-label"><?php _l('labeler::allow_label_manager')?></label>
    <div class="col-sm-5">
        <select name="val[allow_label_manager]" class="form-control form-control-sm">
            <option value="0"<?php echo config('allow_label_manager') == 0 ? ' selected="selected"' : ' '?>><?php _l('labeler::not_allowed')?></option>
            <option value="1"<?php echo config('allow_label_manager') == 1 ? ' selected="selected"' : ' '?>><?php _l('labeler::allowed')?></option>
        </select> 
        <span class="text-muted"><?php _l('labeler::allow_label_manager_info')?></span>
    </div>
</div> 
